apiVersion: v1
items:
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: greeter
    name: greeter
    namespace: {{ .Release.Namespace }}
  spec:
    host: {{ .Release.Namespace }}.{{ appSuffix}}
    port:
      targetPort: 8080
    to:
      kind: Service
      name: greeter
      weight: 100
    wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""

